import { i } from '@instantdb/react';

const _schema = i.schema({
  entities: {
    $users: i.entity({
      email: i.string().unique().indexed().optional(),
      newsletterConsent: i.boolean().optional(),
      createdAt: i.string().optional(),
    }),
    companies: i.entity({
      ticker: i.string().unique().indexed(),
      name: i.string().indexed(),
      exchange: i.string(),
      sector: i.string(),
      industry: i.string(),
      description: i.string(),
      website: i.string(),
      logoUrl: i.string().optional(),
    }),
    briefs: i.entity({
      companyId: i.string().indexed(),
      ticker: i.string().indexed(),
      title: i.string(),
      slug: i.string().unique().indexed(),
      publishDate: i.string().indexed(),
      status: i.string().indexed(),
      summary: i.string(),
      ownerQuestion: i.string(),
      disclaimer: i.string(),
    }),
    briefSections: i.entity({
      briefId: i.string().indexed(),
      slug: i.string().indexed(),
      title: i.string(),
      sectionType: i.string().indexed(),
      summary: i.string(),
      body: i.string(),
      order: i.number().indexed(),
      updatedAt: i.string(),
    }),
    sectionBlocks: i.entity({
      sectionId: i.string().indexed(),
      blockType: i.string().indexed(),
      title: i.string().optional(),
      content: i.any(),
      sortOrder: i.number().indexed(),
    }),
    financialMetrics: i.entity({
      companyId: i.string().indexed(),
      period: i.string().indexed(),
      fiscalYear: i.number().indexed(),
      fiscalQuarter: i.string().indexed(),
      metricName: i.string().indexed(),
      value: i.number(),
      unit: i.string(),
      sourceLabel: i.string(),
    }),
    earningsEvents: i.entity({
      companyId: i.string().indexed(),
      fiscalPeriod: i.string().indexed(),
      reportDate: i.string().indexed(),
      revenue: i.number(),
      eps: i.number(),
      grossMargin: i.number(),
      operatingIncome: i.number(),
      netIncome: i.number(),
      notes: i.string(),
    }),
    transcriptNotes: i.entity({
      briefId: i.string().indexed(),
      speaker: i.string(),
      topic: i.string().indexed(),
      quoteSnippet: i.string(),
      ownerInterpretation: i.string(),
      sentiment: i.string().indexed(),
    }),
    watchlistItems: i.entity({
      userId: i.string().indexed(),
      companyId: i.string().indexed(),
      createdAt: i.string(),
      notes: i.string().optional(),
    }),
    portfolioPositions: i.entity({
      userId: i.string().indexed(),
      companyId: i.string().indexed(),
      shares: i.number(),
      averageCost: i.number(),
      thesis: i.string(),
      createdAt: i.string(),
      updatedAt: i.string(),
    }),
    savedBriefs: i.entity({
      userId: i.string().indexed(),
      briefId: i.string().indexed(),
      createdAt: i.string(),
    }),
    userProfiles: i.entity({
      userId: i.string().unique().indexed(),
      email: i.string().indexed(),
      createdAt: i.string(),
      newsletterConsent: i.boolean(),
    }),
  },
});

export default _schema;
